/**
 * Autoclickers and Passive Income Module
 */
const AutoclickerRegistry = {
    data: [
        {
            id: 'auto_01',
            name: 'Микро-демон',
            desc: 'Фоновый процесс, перехватывающий кредиты ядра. Базовый +0.2 CPS.',
            baseCps: 0.2,
            baseCost: 50,
            costMult: 1.15,
            upgradeBaseCost: 150,
            upgradeCostMult: 1.5,
            icon: '👾'
        },
        {
            id: 'auto_02',
            name: 'Скрипт авто-взлома',
            desc: 'Автоматизирует простейшие эксплойты командной строки. Базовый +1.5 CPS.',
            baseCps: 1.5,
            baseCost: 250,
            costMult: 1.15,
            upgradeBaseCost: 750,
            upgradeCostMult: 1.6,
            icon: '📜'
        },
        {
            id: 'auto_03',
            name: 'Нейросетевой бот',
            desc: 'Автономный ИИ-агент, сканирующий утечки памяти. Базовый +8.0 CPS.',
            baseCps: 8.0,
            baseCost: 1800,
            costMult: 1.16,
            upgradeBaseCost: 4000,
            upgradeCostMult: 1.7,
            icon: '🤖'
        },
        {
            id: 'auto_04',
            name: 'Узел подсети',
            desc: 'Выделенный виртуальный сервер для майнинга циклов ядра. Базовый +50 CPS.',
            baseCps: 50.0,
            baseCost: 12000,
            costMult: 1.18,
            upgradeBaseCost: 25000,
            upgradeCostMult: 1.8,
            icon: '🖥️'
        },
        {
            id: 'auto_05',
            name: 'Квантовый дата-центр',
            desc: 'Коммерческая серверная ферма с квантовым превосходством. Базовый +300 CPS.',
            baseCps: 300.0,
            baseCost: 85000,
            costMult: 1.20,
            upgradeBaseCost: 180000,
            upgradeCostMult: 1.9,
            icon: '🏢'
        },
        {
            id: 'auto_06',
            name: 'ИИ-сингулярность «Нексус»',
            desc: 'Самообучающаяся сущность, поглощающая ресурсы глобальной сети. Базовый +1800 CPS.',
            baseCps: 1800.0,
            baseCost: 650000,
            costMult: 1.22,
            upgradeBaseCost: 1200000,
            upgradeCostMult: 2.0,
            icon: '🧠'
        }
    ],

    // Local runtime variables
    timerId: null,
    lastTick: Date.now(),

    // Retrieve owned count
    getCount(id) {
        return GameState.autoclickers[id]?.count || 0;
    },

    // Retrieve upgrade level
    getUpgradeLevel(id) {
        return GameState.autoclickers[id]?.upgradeLevel || 0;
    },

    // Get current purchase cost
    getCost(autoclicker) {
        const count = this.getCount(autoclicker.id);
        return Math.floor(autoclicker.baseCost * Math.pow(autoclicker.costMult, count));
    },

    // Get current upgrade cost
    getUpgradeCost(autoclicker) {
        const lvl = this.getUpgradeLevel(autoclicker.id);
        return Math.floor(autoclicker.upgradeBaseCost * Math.pow(autoclicker.upgradeCostMult, lvl));
    },

    // Calculate CPS generated by single autoclicker type
    getCpsForType(autoclicker) {
        const count = this.getCount(autoclicker.id);
        if (count === 0) return 0;
        
        const lvl = this.getUpgradeLevel(autoclicker.id);
        // Each upgrade level doubles its effectiveness (+100% bonus)
        const multiplier = Math.pow(2, lvl);
        return autoclicker.baseCps * count * multiplier;
    },

    // Try to purchase autoclicker unit
    buyAutoclicker(id) {
        const autoclicker = this.data.find(a => a.id === id);
        if (!autoclicker) return false;

        const cost = this.getCost(autoclicker);
        if (GameState.spendCredits(cost)) {
            if (!GameState.autoclickers[id]) {
                GameState.autoclickers[id] = { count: 0, upgradeLevel: 0 };
            }
            GameState.autoclickers[id].count++;
            GameState.stats.upgradesBought++;
            
            this.recalculateCPS();
            AudioEngine.playBuy();
            GameState.saveGame();
            
            // Check Achievements
            if (window.Game && Game.AchievementsRegistry) {
                Game.AchievementsRegistry.checkUnlocks();
            }

            return true;
        }
        return false;
    },

    // Try to purchase upgrade for autoclicker
    buyAutoclickerUpgrade(id) {
        const autoclicker = this.data.find(a => a.id === id);
        if (!autoclicker) return false;

        // Must own at least one unit before upgrading it
        if (this.getCount(id) === 0) return false;

        const cost = this.getUpgradeCost(autoclicker);
        if (GameState.spendCredits(cost)) {
            GameState.autoclickers[id].upgradeLevel++;
            GameState.stats.upgradesBought++;

            this.recalculateCPS();
            AudioEngine.playBuy();
            GameState.saveGame();
            return true;
        }
        return false;
    },

    // Calculate total CPS
    recalculateCPS() {
        let totalCps = 0;
        this.data.forEach(a => {
            totalCps += this.getCpsForType(a);
        });

        // Apply global multiplier upgrades (e.g. quantum compiler)
        let globalMult = 1.0;
        if (window.UpgradesRegistry) {
            const compilerLvl = window.UpgradesRegistry.getLevel('global_01');
            globalMult += compilerLvl * 0.10;
        }

        // Apply Nanocores multiplier (2% per Nanocore)
        const nanocoresMult = 1.0 + (GameState.nanocores || 0) * 0.02;

        // Apply Prestige Neural Net Overdrive upgrade (+10% per level)
        let prestigeCpsMult = 1.0;
        if (window.PrestigeRegistry) {
            const netOverdriveLvl = window.PrestigeRegistry.getLevel('pres_cps_boost');
            prestigeCpsMult += netOverdriveLvl * 0.10;
        }

        // Apply active temporary buffs
        const activeBuffMult = GameState.getActiveCpsMultiplier();
        
        GameState.cps = totalCps * globalMult * nanocoresMult * prestigeCpsMult * activeBuffMult;

        // Statistics
        if (GameState.cps > GameState.stats.maxCps) {
            GameState.stats.maxCps = GameState.cps;
        }
    },

    // Start tick runner (runs 10 times a second for visually smooth coin accumulation)
    startTicking() {
        this.lastTick = Date.now();
        this.timerId = setInterval(() => {
            this.tick();
        }, 100);
    },

    stopTicking() {
        if (this.timerId) {
            clearInterval(this.timerId);
            this.timerId = null;
        }
    },

    tick() {
        const now = Date.now();
        const deltaSec = (now - this.lastTick) / 1000;
        this.lastTick = now;

        if (GameState.cps > 0 && deltaSec > 0) {
            const earned = GameState.cps * deltaSec;
            
            // Bypass global click multiplier for passive ticks, but add level exp
            GameState.credits += earned;
            GameState.totalCreditsEarned += earned;
            GameState.totalEarnedThisRun += earned;
            GameState.stats.totalEarned += earned;

            // Generate EXP passively (1% of CPS earned is converted to exp)
            const passiveExp = Math.max(0, earned * 0.1);
            GameState.gainExp(passiveExp);

            // Trigger UI update
            if (window.Game && Game.UI) {
                Game.UI.updateCurrencyDisplay();
            }
        }
    }
};
// Make globally available
window.AutoclickerRegistry = AutoclickerRegistry;
